version: '3.9'
services:
  gateway:
    build: .
    command: /cmd
    depends_on:
      - cache
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "cache"
      REDIS_PORT: ":6379"
    links:
      - cache
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache: